//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSQA
    {
        public int Survey_Id { get; set; }
        public int Section_Id { get; set; }
        public int Question_Id { get; set; }
        public int Answer_Id { get; set; }
        public int Respondent_Id { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Respondent Respondent { get; set; }
        public virtual Section Section { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
