//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Respondents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Respondents()
        {
            this.TBL_RSQA = new HashSet<TBL_RSQA>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Age { get; set; }
        public int Gender { get; set; }
        public string Degree { get; set; }
        public string DurationMarried { get; set; }
        public string Major { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RSQA> TBL_RSQA { get; set; }
    }
}
